openapi: 3.1.0
info:
  version: 1.0.0
  title: API First Json2Pojo
  termsOfService: https://example.com/terms/
  contact:
    name: Contact our support
    email: jbb@gmail.com
    url: http://springframework.guru/contact
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  x-logo:
    url: https://redocly.github.io/openapi-template/logo.png
    altText: OpenAPI example logo
  description: |
    This is an **example** API to demonstrate features of the OpenAPI specification.
    # Introduction
servers:
  - url: https://{tenant}/api/v1
    variables:
      tenant:
        default: www
        description: Your tenant id
  - url: https://example.com/api/v1
security:
  - basic_auth: []
tags:
  - name: Conversion
    description: Conversion operations
externalDocs:
  description: Find out how to create a GitHub repo for your OpenAPI definition.
  url: https://github.com/Redocly/create-openapi-repo
paths:
  /v1/convert/{website}:
    $ref: 'paths/convert_{client}.yaml'
components:
  securitySchemes:
    main_auth:
      description: Example description text of the OAuth2 scheme.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://example.com/api/oauth/dialog
          scopes:
            read:users: read user info
            write:users: modify or remove users
    api_key:
      description: Example description text of the API key scheme.
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic
  schemas:
    conversionResult:
      $ref: 'components/schemas/ConversionResult.yaml'